// This file needs to be in a separate folder,
// because it is too long to be processed by JSDoc.
// Else it will throw an error when the doc website runs its script.
const ICON_TYPES = [
    {
        title: 'Standard',
        value: 'standard',
        icons: [
            { title: 'account', value: 'standard:account' },
            {
                title: 'action_list_component',
                value: 'standard:action_list_component'
            },
            {
                title: 'actions_and_buttons',
                value: 'standard:actions_and_buttons'
            },
            { title: 'activation_target', value: 'standard:activation_target' },
            { title: 'activations', value: 'standard:activations' },
            { title: 'address', value: 'standard:address' },
            { title: 'agent_session', value: 'standard:agent_session' },
            { title: 'all', value: 'standard:all' },
            { title: 'announcement', value: 'standard:announcement' },
            { title: 'answer_best', value: 'standard:answer_best' },
            { title: 'answer_private', value: 'standard:answer_private' },
            { title: 'answer_public', value: 'standard:answer_public' },
            { title: 'apex_plugin', value: 'standard:apex_plugin' },
            { title: 'apex', value: 'standard:apex' },
            { title: 'app', value: 'standard:app' },
            { title: 'approval', value: 'standard:approval' },
            { title: 'apps_admin', value: 'standard:apps_admin' },
            { title: 'apps', value: 'standard:apps' },
            { title: 'article', value: 'standard:article' },
            {
                title: 'asset_action_source',
                value: 'standard:asset_action_source'
            },
            { title: 'asset_action', value: 'standard:asset_action' },
            {
                title: 'asset_downtime_period',
                value: 'standard:asset_downtime_period'
            },
            { title: 'asset_object', value: 'standard:asset_object' },
            {
                title: 'asset_relationship',
                value: 'standard:asset_relationship'
            },
            {
                title: 'asset_state_period',
                value: 'standard:asset_state_period'
            },
            { title: 'asset_warranty', value: 'standard:asset_warranty' },
            { title: 'assigned_resource', value: 'standard:assigned_resource' },
            { title: 'assignment', value: 'standard:assignment' },
            { title: 'avatar_loading', value: 'standard:avatar_loading' },
            { title: 'avatar', value: 'standard:avatar' },
            { title: 'bot_training', value: 'standard:bot_training' },
            { title: 'bot', value: 'standard:bot' },
            { title: 'branch_merge', value: 'standard:branch_merge' },
            { title: 'brand', value: 'standard:brand' },
            { title: 'business_hours', value: 'standard:business_hours' },
            { title: 'buyer_account', value: 'standard:buyer_account' },
            { title: 'buyer_group', value: 'standard:buyer_group' },
            { title: 'calibration', value: 'standard:calibration' },
            { title: 'call_coaching', value: 'standard:call_coaching' },
            { title: 'call_history', value: 'standard:call_history' },
            { title: 'call', value: 'standard:call' },
            { title: 'campaign_members', value: 'standard:campaign_members' },
            { title: 'campaign', value: 'standard:campaign' },
            { title: 'cancel_checkout', value: 'standard:cancel_checkout' },
            { title: 'canvas', value: 'standard:canvas' },
            { title: 'carousel', value: 'standard:carousel' },
            {
                title: 'case_change_status',
                value: 'standard:case_change_status'
            },
            { title: 'case_comment', value: 'standard:case_comment' },
            { title: 'case_email', value: 'standard:case_email' },
            { title: 'case_log_a_call', value: 'standard:case_log_a_call' },
            { title: 'case_milestone', value: 'standard:case_milestone' },
            { title: 'case_transcript', value: 'standard:case_transcript' },
            { title: 'case_wrap_up', value: 'standard:case_wrap_up' },
            { title: 'case', value: 'standard:case' },
            { title: 'catalog', value: 'standard:catalog' },
            { title: 'category', value: 'standard:category' },
            {
                title: 'channel_program_history',
                value: 'standard:channel_program_history'
            },
            {
                title: 'channel_program_levels',
                value: 'standard:channel_program_levels'
            },
            {
                title: 'channel_program_members',
                value: 'standard:channel_program_members'
            },
            { title: 'channel_programs', value: 'standard:channel_programs' },
            { title: 'chart', value: 'standard:chart' },
            { title: 'checkout', value: 'standard:checkout' },
            { title: 'choice', value: 'standard:choice' },
            { title: 'client', value: 'standard:client' },
            { title: 'cms', value: 'standard:cms' },
            { title: 'coaching', value: 'standard:coaching' },
            { title: 'code_playground', value: 'standard:code_playground' },
            {
                title: 'collection_variable',
                value: 'standard:collection_variable'
            },
            { title: 'collection', value: 'standard:collection' },
            { title: 'connected_apps', value: 'standard:connected_apps' },
            { title: 'constant', value: 'standard:constant' },
            { title: 'contact_list', value: 'standard:contact_list' },
            { title: 'contact_request', value: 'standard:contact_request' },
            { title: 'contact', value: 'standard:contact' },
            {
                title: 'contract_line_item',
                value: 'standard:contract_line_item'
            },
            { title: 'contract', value: 'standard:contract' },
            { title: 'currency_input', value: 'standard:currency_input' },
            { title: 'currency', value: 'standard:currency' }
        ],
        iconsExtended: [
            {
                title: 'custom_component_task',
                value: 'standard:custom_component_task'
            },
            {
                title: 'custom_notification',
                value: 'standard:custom_notification'
            },
            { title: 'custom', value: 'standard:custom' },
            { title: 'customer_360', value: 'standard:customer_360' },
            {
                title: 'customer_lifecycle_analytics',
                value: 'standard:customer_lifecycle_analytics'
            },
            {
                title: 'customer_portal_users',
                value: 'standard:customer_portal_users'
            },
            { title: 'customers', value: 'standard:customers' },
            { title: 'dashboard_ea', value: 'standard:dashboard_ea' },
            { title: 'dashboard', value: 'standard:dashboard' },
            {
                title: 'data_integration_hub',
                value: 'standard:data_integration_hub'
            },
            { title: 'data_mapping', value: 'standard:data_mapping' },
            { title: 'data_model', value: 'standard:data_model' },
            { title: 'data_streams', value: 'standard:data_streams' },
            { title: 'datadotcom', value: 'standard:datadotcom' },
            { title: 'dataset', value: 'standard:dataset' },
            { title: 'date_input', value: 'standard:date_input' },
            { title: 'date_time', value: 'standard:date_time' },
            { title: 'decision', value: 'standard:decision' },
            { title: 'default', value: 'standard:default' },
            { title: 'delegated_account', value: 'standard:delegated_account' },
            { title: 'device', value: 'standard:device' },
            { title: 'display_rich_text', value: 'standard:display_rich_text' },
            { title: 'display_text', value: 'standard:display_text' },
            { title: 'document', value: 'standard:document' },
            { title: 'drafts', value: 'standard:drafts' },
            {
                title: 'dynamic_record_choice',
                value: 'standard:dynamic_record_choice'
            },
            { title: 'education', value: 'standard:education' },
            { title: 'einstein_replies', value: 'standard:einstein_replies' },
            { title: 'email_chatter', value: 'standard:email_chatter' },
            { title: 'email', value: 'standard:email' },
            { title: 'employee_asset', value: 'standard:employee_asset' },
            { title: 'employee_contact', value: 'standard:employee_contact' },
            {
                title: 'employee_job_position',
                value: 'standard:employee_job_position'
            },
            { title: 'employee_job', value: 'standard:employee_job' },
            {
                title: 'employee_organization',
                value: 'standard:employee_organization'
            },
            { title: 'employee', value: 'standard:employee' },
            { title: 'empty', value: 'standard:empty' },
            { title: 'endorsement', value: 'standard:endorsement' },
            {
                title: 'entitlement_policy',
                value: 'standard:entitlement_policy'
            },
            {
                title: 'entitlement_process',
                value: 'standard:entitlement_process'
            },
            {
                title: 'entitlement_template',
                value: 'standard:entitlement_template'
            },
            { title: 'entitlement', value: 'standard:entitlement' },
            { title: 'entity_milestone', value: 'standard:entity_milestone' },
            { title: 'entity', value: 'standard:entity' },
            { title: 'environment_hub', value: 'standard:environment_hub' },
            { title: 'event', value: 'standard:event' },
            { title: 'events', value: 'standard:events' },
            {
                title: 'expense_report_entry',
                value: 'standard:expense_report_entry'
            },
            { title: 'expense_report', value: 'standard:expense_report' },
            { title: 'expense', value: 'standard:expense' },
            { title: 'feed', value: 'standard:feed' },
            { title: 'feedback', value: 'standard:feedback' },
            { title: 'file', value: 'standard:file' },
            {
                title: 'filter_criteria_rule',
                value: 'standard:filter_criteria_rule'
            },
            { title: 'filter_criteria', value: 'standard:filter_criteria' },
            { title: 'filter', value: 'standard:filter' },
            { title: 'first_non_empty', value: 'standard:first_non_empty' },
            { title: 'flow', value: 'standard:flow' },
            { title: 'folder', value: 'standard:folder' },
            { title: 'forecasts', value: 'standard:forecasts' },
            { title: 'form', value: 'standard:form' },
            { title: 'formula', value: 'standard:formula' },
            { title: 'fulfillment_order', value: 'standard:fulfillment_order' },
            { title: 'generic_loading', value: 'standard:generic_loading' },
            { title: 'global_constant', value: 'standard:global_constant' },
            { title: 'goals', value: 'standard:goals' },
            { title: 'group_loading', value: 'standard:group_loading' },
            { title: 'groups', value: 'standard:groups' },
            { title: 'guidance_center', value: 'standard:guidance_center' },
            { title: 'hierarchy', value: 'standard:hierarchy' },
            {
                title: 'high_velocity_sales',
                value: 'standard:high_velocity_sales'
            },
            {
                title: 'holiday_operating_hours',
                value: 'standard:holiday_operating_hours'
            },
            { title: 'home', value: 'standard:home' },
            { title: 'household', value: 'standard:household' },
            { title: 'immunization', value: 'standard:immunization' },
            { title: 'individual', value: 'standard:individual' },
            { title: 'insights', value: 'standard:insights' },
            { title: 'instore_locations', value: 'standard:instore_locations' },
            {
                title: 'investment_account',
                value: 'standard:investment_account'
            },
            { title: 'invocable_action', value: 'standard:invocable_action' },
            { title: 'iot_context', value: 'standard:iot_context' },
            {
                title: 'iot_orchestrations',
                value: 'standard:iot_orchestrations'
            },
            { title: 'javascript_button', value: 'standard:javascript_button' },
            { title: 'job_family', value: 'standard:job_family' },
            { title: 'job_position', value: 'standard:job_position' },
            { title: 'job_profile', value: 'standard:job_profile' },
            { title: 'kanban', value: 'standard:kanban' },
            { title: 'key_dates', value: 'standard:key_dates' },
            { title: 'knowledge', value: 'standard:knowledge' },
            { title: 'lead_insights', value: 'standard:lead_insights' },
            { title: 'lead_list', value: 'standard:lead_list' },
            { title: 'lead', value: 'standard:lead' },
            { title: 'letterhead', value: 'standard:letterhead' },
            {
                title: 'lightning_component',
                value: 'standard:lightning_component'
            },
            { title: 'lightning_usage', value: 'standard:lightning_usage' },
            { title: 'link', value: 'standard:link' },
            { title: 'list_email', value: 'standard:list_email' },
            { title: 'live_chat_visitor', value: 'standard:live_chat_visitor' },
            { title: 'live_chat', value: 'standard:live_chat' },
            { title: 'location_permit', value: 'standard:location_permit' },
            { title: 'location', value: 'standard:location' },
            { title: 'log_a_call', value: 'standard:log_a_call' },
            { title: 'logging', value: 'standard:logging' },
            { title: 'loop', value: 'standard:loop' },
            { title: 'macros', value: 'standard:macros' },
            { title: 'maintenance_asset', value: 'standard:maintenance_asset' },
            { title: 'maintenance_plan', value: 'standard:maintenance_plan' },
            {
                title: 'maintenance_work_rule',
                value: 'standard:maintenance_work_rule'
            },
            { title: 'marketing_actions', value: 'standard:marketing_actions' },
            { title: 'merge', value: 'standard:merge' },
            {
                title: 'messaging_conversation',
                value: 'standard:messaging_conversation'
            },
            { title: 'messaging_session', value: 'standard:messaging_session' },
            { title: 'messaging_user', value: 'standard:messaging_user' },
            { title: 'metrics', value: 'standard:metrics' },
            { title: 'multi_picklist', value: 'standard:multi_picklist' },
            {
                title: 'multi_select_checkbox',
                value: 'standard:multi_select_checkbox'
            },
            { title: 'news', value: 'standard:news' },
            { title: 'note', value: 'standard:note' },
            { title: 'number_input', value: 'standard:number_input' },
            {
                title: 'observation_component',
                value: 'standard:observation_component'
            },
            { title: 'omni_supervisor', value: 'standard:omni_supervisor' },
            { title: 'operating_hours', value: 'standard:operating_hours' },
            {
                title: 'opportunity_contact_role',
                value: 'standard:opportunity_contact_role'
            },
            {
                title: 'opportunity_splits',
                value: 'standard:opportunity_splits'
            },
            { title: 'opportunity', value: 'standard:opportunity' },
            { title: 'order_item', value: 'standard:order_item' },
            { title: 'orders', value: 'standard:orders' },
            { title: 'outcome', value: 'standard:outcome' },
            { title: 'output', value: 'standard:output' },
            {
                title: 'partner_fund_allocation',
                value: 'standard:partner_fund_allocation'
            },
            {
                title: 'partner_fund_claim',
                value: 'standard:partner_fund_claim'
            },
            {
                title: 'partner_fund_request',
                value: 'standard:partner_fund_request'
            },
            {
                title: 'partner_marketing_budget',
                value: 'standard:partner_marketing_budget'
            },
            { title: 'partners', value: 'standard:partners' },
            { title: 'password', value: 'standard:password' },
            { title: 'past_chat', value: 'standard:past_chat' },
            { title: 'payment_gateway', value: 'standard:payment_gateway' },
            { title: 'people', value: 'standard:people' },
            { title: 'performance', value: 'standard:performance' },
            { title: 'person_account', value: 'standard:person_account' },
            { title: 'photo', value: 'standard:photo' },
            { title: 'picklist_choice', value: 'standard:picklist_choice' },
            { title: 'picklist_type', value: 'standard:picklist_type' },
            { title: 'planogram', value: 'standard:planogram' },
            { title: 'poll', value: 'standard:poll' },
            {
                title: 'portal_roles_and_subordinates',
                value: 'standard:portal_roles_and_subordinates'
            },
            { title: 'portal_roles', value: 'standard:portal_roles' },
            { title: 'portal', value: 'standard:portal' },
            { title: 'post', value: 'standard:post' },
            { title: 'practitioner_role', value: 'standard:practitioner_role' },
            {
                title: 'price_book_entries',
                value: 'standard:price_book_entries'
            },
            { title: 'price_books', value: 'standard:price_books' },
            { title: 'pricebook', value: 'standard:pricebook' },
            { title: 'pricing_workspace', value: 'standard:pricing_workspace' },
            { title: 'procedure_detail', value: 'standard:procedure_detail' },
            { title: 'procedure', value: 'standard:procedure' },
            { title: 'process_exception', value: 'standard:process_exception' },
            { title: 'process', value: 'standard:process' },
            { title: 'product_consumed', value: 'standard:product_consumed' },
            {
                title: 'product_item_transaction',
                value: 'standard:product_item_transaction'
            },
            { title: 'product_item', value: 'standard:product_item' },
            {
                title: 'product_request_line_item',
                value: 'standard:product_request_line_item'
            },
            { title: 'product_request', value: 'standard:product_request' },
            { title: 'product_required', value: 'standard:product_required' },
            {
                title: 'product_service_campaign_item',
                value: 'standard:product_service_campaign_item'
            },
            {
                title: 'product_service_campaign',
                value: 'standard:product_service_campaign'
            },
            { title: 'product_transfer', value: 'standard:product_transfer' },
            {
                title: 'product_warranty_term',
                value: 'standard:product_warranty_term'
            },
            { title: 'product_workspace', value: 'standard:product_workspace' },
            { title: 'product', value: 'standard:product' },
            { title: 'products', value: 'standard:products' },
            { title: 'proposition', value: 'standard:proposition' },
            { title: 'question_best', value: 'standard:question_best' },
            { title: 'question_feed', value: 'standard:question_feed' },
            { title: 'queue', value: 'standard:queue' },
            { title: 'quick_text', value: 'standard:quick_text' },
            { title: 'quip_sheet', value: 'standard:quip_sheet' },
            { title: 'quip', value: 'standard:quip' },
            { title: 'quotes', value: 'standard:quotes' },
            { title: 'radio_button', value: 'standard:radio_button' },
            { title: 'read_receipts', value: 'standard:read_receipts' },
            { title: 'recent', value: 'standard:recent' },
            { title: 'recipe', value: 'standard:recipe' },
            { title: 'record_create', value: 'standard:record_create' },
            { title: 'record_delete', value: 'standard:record_delete' },
            { title: 'record_lookup', value: 'standard:record_lookup' },
            {
                title: 'record_signature_task',
                value: 'standard:record_signature_task'
            },
            { title: 'record_update', value: 'standard:record_update' },
            { title: 'record', value: 'standard:record' },
            { title: 'recycle_bin', value: 'standard:recycle_bin' },
            { title: 'related_list', value: 'standard:related_list' },
            { title: 'relationship', value: 'standard:relationship' },
            { title: 'reply_text', value: 'standard:reply_text' },
            { title: 'report', value: 'standard:report' },
            { title: 'resource_absence', value: 'standard:resource_absence' },
            { title: 'resource_capacity', value: 'standard:resource_capacity' },
            {
                title: 'resource_preference',
                value: 'standard:resource_preference'
            },
            { title: 'resource_skill', value: 'standard:resource_skill' },
            {
                title: 'return_order_line_item',
                value: 'standard:return_order_line_item'
            },
            { title: 'return_order', value: 'standard:return_order' },
            { title: 'reward', value: 'standard:reward' },
            { title: 'rtc_presence', value: 'standard:rtc_presence' },
            {
                title: 'sales_cadence_target',
                value: 'standard:sales_cadence_target'
            },
            { title: 'sales_cadence', value: 'standard:sales_cadence' },
            { title: 'sales_channel', value: 'standard:sales_channel' },
            { title: 'sales_path', value: 'standard:sales_path' },
            { title: 'sales_value', value: 'standard:sales_value' },
            { title: 'salesforce_cms', value: 'standard:salesforce_cms' },
            { title: 'scan_card', value: 'standard:scan_card' },
            {
                title: 'schedule_objective',
                value: 'standard:schedule_objective'
            },
            {
                title: 'scheduling_constraint',
                value: 'standard:scheduling_constraint'
            },
            { title: 'scheduling_policy', value: 'standard:scheduling_policy' },
            { title: 'screen', value: 'standard:screen' },
            { title: 'search', value: 'standard:search' },
            { title: 'section', value: 'standard:section' },
            { title: 'segments', value: 'standard:segments' },
            {
                title: 'serialized_product_transaction',
                value: 'standard:serialized_product_transaction'
            },
            {
                title: 'serialized_product',
                value: 'standard:serialized_product'
            },
            {
                title: 'service_appointment_capacity_usage',
                value: 'standard:service_appointment_capacity_usage'
            },
            {
                title: 'service_appointment',
                value: 'standard:service_appointment'
            },
            { title: 'service_contract', value: 'standard:service_contract' },
            {
                title: 'service_crew_member',
                value: 'standard:service_crew_member'
            },
            { title: 'service_crew', value: 'standard:service_crew' },
            { title: 'service_report', value: 'standard:service_report' },
            {
                title: 'service_request_detail',
                value: 'standard:service_request_detail'
            },
            { title: 'service_request', value: 'standard:service_request' },
            { title: 'service_resource', value: 'standard:service_resource' },
            {
                title: 'service_territory_location',
                value: 'standard:service_territory_location'
            },
            {
                title: 'service_territory_member',
                value: 'standard:service_territory_member'
            },
            { title: 'service_territory', value: 'standard:service_territory' },
            { title: 'settings', value: 'standard:settings' },
            {
                title: 'shift_pattern_entry',
                value: 'standard:shift_pattern_entry'
            },
            { title: 'shift_pattern', value: 'standard:shift_pattern' },
            { title: 'shift_preference', value: 'standard:shift_preference' },
            { title: 'shift_template', value: 'standard:shift_template' },
            { title: 'shift_type', value: 'standard:shift_type' },
            { title: 'shift', value: 'standard:shift' },
            { title: 'shipment', value: 'standard:shipment' },
            { title: 'skill_entity', value: 'standard:skill_entity' },
            { title: 'skill_requirement', value: 'standard:skill_requirement' },
            { title: 'skill', value: 'standard:skill' },
            { title: 'slider', value: 'standard:slider' },
            { title: 'sms', value: 'standard:sms' },
            { title: 'snippet', value: 'standard:snippet' },
            { title: 'snippets', value: 'standard:snippets' },
            {
                title: 'sobject_collection',
                value: 'standard:sobject_collection'
            },
            { title: 'sobject', value: 'standard:sobject' },
            { title: 'social', value: 'standard:social' },
            { title: 'solution', value: 'standard:solution' },
            { title: 'sort', value: 'standard:sort' },
            { title: 'sossession', value: 'standard:sossession' },
            { title: 'stage_collection', value: 'standard:stage_collection' },
            { title: 'stage', value: 'standard:stage' },
            { title: 'steps', value: 'standard:steps' },
            { title: 'store_group', value: 'standard:store_group' },
            { title: 'store', value: 'standard:store' },
            { title: 'story', value: 'standard:story' },
            { title: 'strategy', value: 'standard:strategy' },
            { title: 'survey', value: 'standard:survey' },
            { title: 'swarm_request', value: 'standard:swarm_request' },
            {
                title: 'system_and_global_variable',
                value: 'standard:system_and_global_variable'
            },
            { title: 'task', value: 'standard:task' },
            { title: 'task2', value: 'standard:task2' },
            { title: 'team_member', value: 'standard:team_member' },
            { title: 'template', value: 'standard:template' },
            { title: 'text_template', value: 'standard:text_template' },
            { title: 'text', value: 'standard:text' },
            { title: 'textarea', value: 'standard:textarea' },
            { title: 'textbox', value: 'standard:textbox' },
            { title: 'thanks_loading', value: 'standard:thanks_loading' },
            { title: 'thanks', value: 'standard:thanks' },
            { title: 'timesheet_entry', value: 'standard:timesheet_entry' },
            { title: 'timesheet', value: 'standard:timesheet' },
            { title: 'timeslot', value: 'standard:timeslot' },
            { title: 'today', value: 'standard:today' },
            { title: 'toggle', value: 'standard:toggle' },
            { title: 'topic', value: 'standard:topic' },
            { title: 'topic2', value: 'standard:topic2' },
            { title: 'trailhead_alt', value: 'standard:trailhead_alt' },
            { title: 'trailhead', value: 'standard:trailhead' },
            { title: 'travel_mode', value: 'standard:travel_mode' },
            { title: 'unmatched', value: 'standard:unmatched' },
            { title: 'user_role', value: 'standard:user_role' },
            { title: 'user', value: 'standard:user' },
            { title: 'variable', value: 'standard:variable' },
            {
                title: 'variation_attribute_setup',
                value: 'standard:variation_attribute_setup'
            },
            {
                title: 'variation_products',
                value: 'standard:variation_products'
            },
            { title: 'video', value: 'standard:video' },
            { title: 'visit_templates', value: 'standard:visit_templates' },
            { title: 'visits', value: 'standard:visits' },
            { title: 'visualforce_page', value: 'standard:visualforce_page' },
            { title: 'voice_call', value: 'standard:voice_call' },
            { title: 'waits', value: 'standard:waits' },
            { title: 'warranty_term', value: 'standard:warranty_term' },
            { title: 'webcart', value: 'standard:webcart' },
            {
                title: 'work_capacity_limit',
                value: 'standard:work_capacity_limit'
            },
            {
                title: 'work_capacity_usage',
                value: 'standard:work_capacity_usage'
            },
            { title: 'work_contract', value: 'standard:work_contract' },
            { title: 'work_order_item', value: 'standard:work_order_item' },
            { title: 'work_order', value: 'standard:work_order' },
            { title: 'work_plan_rule', value: 'standard:work_plan_rule' },
            {
                title: 'work_plan_template_entry',
                value: 'standard:work_plan_template_entry'
            },
            {
                title: 'work_plan_template',
                value: 'standard:work_plan_template'
            },
            { title: 'work_plan', value: 'standard:work_plan' },
            { title: 'work_queue', value: 'standard:work_queue' },
            {
                title: 'work_step_template',
                value: 'standard:work_step_template'
            },
            { title: 'work_step', value: 'standard:work_step' },
            { title: 'work_type_group', value: 'standard:work_type_group' },
            { title: 'work_type', value: 'standard:work_type' }
        ]
    },
    {
        title: 'Custom',
        value: 'custom',
        icons: [
            { title: 'custom1', value: 'custom:custom1' },
            { title: 'custom2', value: 'custom:custom2' },
            { title: 'custom3', value: 'custom:custom3' },
            { title: 'custom4', value: 'custom:custom4' },
            { title: 'custom5', value: 'custom:custom5' },
            { title: 'custom6', value: 'custom:custom6' },
            { title: 'custom7', value: 'custom:custom7' },
            { title: 'custom8', value: 'custom:custom8' },
            { title: 'custom9', value: 'custom:custom9' },
            { title: 'custom10', value: 'custom:custom10' },
            { title: 'custom11', value: 'custom:custom11' },
            { title: 'custom12', value: 'custom:custom12' },
            { title: 'custom13', value: 'custom:custom13' },
            { title: 'custom14', value: 'custom:custom14' },
            { title: 'custom15', value: 'custom:custom15' },
            { title: 'custom16', value: 'custom:custom16' },
            { title: 'custom17', value: 'custom:custom17' },
            { title: 'custom18', value: 'custom:custom18' },
            { title: 'custom19', value: 'custom:custom19' },
            { title: 'custom20', value: 'custom:custom20' },
            { title: 'custom21', value: 'custom:custom21' },
            { title: 'custom22', value: 'custom:custom22' },
            { title: 'custom23', value: 'custom:custom23' },
            { title: 'custom24', value: 'custom:custom24' },
            { title: 'custom25', value: 'custom:custom25' },
            { title: 'custom26', value: 'custom:custom26' },
            { title: 'custom27', value: 'custom:custom27' },
            { title: 'custom28', value: 'custom:custom28' },
            { title: 'custom29', value: 'custom:custom29' },
            { title: 'custom30', value: 'custom:custom30' },
            { title: 'custom31', value: 'custom:custom31' },
            { title: 'custom32', value: 'custom:custom32' },
            { title: 'custom33', value: 'custom:custom33' },
            { title: 'custom34', value: 'custom:custom34' },
            { title: 'custom35', value: 'custom:custom35' },
            { title: 'custom36', value: 'custom:custom36' },
            { title: 'custom37', value: 'custom:custom37' },
            { title: 'custom38', value: 'custom:custom38' },
            { title: 'custom39', value: 'custom:custom39' },
            { title: 'custom40', value: 'custom:custom40' },
            { title: 'custom41', value: 'custom:custom41' },
            { title: 'custom42', value: 'custom:custom42' },
            { title: 'custom43', value: 'custom:custom43' },
            { title: 'custom44', value: 'custom:custom44' },
            { title: 'custom45', value: 'custom:custom45' },
            { title: 'custom46', value: 'custom:custom46' },
            { title: 'custom47', value: 'custom:custom47' },
            { title: 'custom48', value: 'custom:custom48' },
            { title: 'custom49', value: 'custom:custom49' },
            { title: 'custom50', value: 'custom:custom50' },
            { title: 'custom51', value: 'custom:custom51' },
            { title: 'custom52', value: 'custom:custom52' },
            { title: 'custom53', value: 'custom:custom53' },
            { title: 'custom54', value: 'custom:custom54' },
            { title: 'custom55', value: 'custom:custom55' },
            { title: 'custom56', value: 'custom:custom56' },
            { title: 'custom57', value: 'custom:custom57' },
            { title: 'custom58', value: 'custom:custom58' },
            { title: 'custom59', value: 'custom:custom59' },
            { title: 'custom60', value: 'custom:custom60' },
            { title: 'custom61', value: 'custom:custom61' },
            { title: 'custom62', value: 'custom:custom62' },
            { title: 'custom63', value: 'custom:custom63' },
            { title: 'custom64', value: 'custom:custom64' },
            { title: 'custom65', value: 'custom:custom65' },
            { title: 'custom66', value: 'custom:custom66' },
            { title: 'custom67', value: 'custom:custom67' },
            { title: 'custom68', value: 'custom:custom68' },
            { title: 'custom69', value: 'custom:custom69' },
            { title: 'custom70', value: 'custom:custom70' },
            { title: 'custom71', value: 'custom:custom71' },
            { title: 'custom72', value: 'custom:custom72' },
            { title: 'custom73', value: 'custom:custom73' },
            { title: 'custom74', value: 'custom:custom74' },
            { title: 'custom75', value: 'custom:custom75' },
            { title: 'custom76', value: 'custom:custom76' },
            { title: 'custom77', value: 'custom:custom77' },
            { title: 'custom78', value: 'custom:custom78' },
            { title: 'custom79', value: 'custom:custom79' },
            { title: 'custom80', value: 'custom:custom80' },
            { title: 'custom81', value: 'custom:custom81' },
            { title: 'custom82', value: 'custom:custom82' },
            { title: 'custom83', value: 'custom:custom83' },
            { title: 'custom84', value: 'custom:custom84' },
            { title: 'custom85', value: 'custom:custom85' },
            { title: 'custom86', value: 'custom:custom86' },
            { title: 'custom87', value: 'custom:custom87' },
            { title: 'custom88', value: 'custom:custom88' },
            { title: 'custom89', value: 'custom:custom89' },
            { title: 'custom90', value: 'custom:custom90' },
            { title: 'custom91', value: 'custom:custom91' },
            { title: 'custom92', value: 'custom:custom92' },
            { title: 'custom93', value: 'custom:custom93' },
            { title: 'custom94', value: 'custom:custom94' },
            { title: 'custom95', value: 'custom:custom95' },
            { title: 'custom96', value: 'custom:custom96' },
            { title: 'custom97', value: 'custom:custom97' },
            { title: 'custom98', value: 'custom:custom98' },
            { title: 'custom99', value: 'custom:custom99' },
            { title: 'custom100', value: 'custom:custom100' },
            { title: 'custom101', value: 'custom:custom101' },
            { title: 'custom102', value: 'custom:custom102' },
            { title: 'custom103', value: 'custom:custom103' },
            { title: 'custom104', value: 'custom:custom104' },
            { title: 'custom105', value: 'custom:custom105' },
            { title: 'custom106', value: 'custom:custom106' },
            { title: 'custom107', value: 'custom:custom107' },
            { title: 'custom108', value: 'custom:custom108' },
            { title: 'custom109', value: 'custom:custom109' },
            { title: 'custom110', value: 'custom:custom110' },
            { title: 'custom111', value: 'custom:custom111' },
            { title: 'custom112', value: 'custom:custom112' },
            { title: 'custom113', value: 'custom:custom113' }
        ]
    },
    {
        title: 'Utility',
        value: 'utility',
        icons: [
            { title: 'activity', value: 'utility:activity' },
            { title: 'ad_set', value: 'utility:ad_set' },
            { title: 'add', value: 'utility:add' },
            { title: 'adduser', value: 'utility:adduser' },
            { title: 'adjust_value', value: 'utility:adjust_value' },
            { title: 'advanced_function', value: 'utility:advanced_function' },
            { title: 'advertising', value: 'utility:advertising' },
            { title: 'agent_session', value: 'utility:agent_session' },
            { title: 'alert', value: 'utility:alert' },
            { title: 'all', value: 'utility:all' },
            { title: 'anchor', value: 'utility:anchor' },
            { title: 'animal_and_nature', value: 'utility:animal_and_nature' },
            { title: 'announcement', value: 'utility:announcement' },
            { title: 'answer', value: 'utility:answer' },
            { title: 'answered_twice', value: 'utility:answered_twice' },
            { title: 'anywhere_alert', value: 'utility:anywhere_alert' },
            { title: 'anywhere_chat', value: 'utility:anywhere_chat' },
            { title: 'apex_plugin', value: 'utility:apex_plugin' },
            { title: 'apex', value: 'utility:apex' },
            { title: 'approval', value: 'utility:approval' },
            { title: 'apps', value: 'utility:apps' },
            { title: 'archive', value: 'utility:archive' },
            { title: 'arrow_bottom', value: 'utility:arrow_bottom' },
            { title: 'arrow_top', value: 'utility:arrow_top' },
            { title: 'arrowdown', value: 'utility:arrowdown' },
            { title: 'arrowup', value: 'utility:arrowup' },
            { title: 'asset_warranty', value: 'utility:asset_warranty' },
            { title: 'assignment', value: 'utility:assignment' },
            { title: 'attach', value: 'utility:attach' },
            { title: 'automate', value: 'utility:automate' },
            { title: 'away', value: 'utility:away' },
            { title: 'back', value: 'utility:back' },
            { title: 'ban', value: 'utility:ban' },
            { title: 'block_visitor', value: 'utility:block_visitor' },
            { title: 'bold', value: 'utility:bold' },
            { title: 'bookmark', value: 'utility:bookmark' },
            { title: 'breadcrumbs', value: 'utility:breadcrumbs' },
            { title: 'broadcast', value: 'utility:broadcast' },
            { title: 'brush', value: 'utility:brush' },
            { title: 'bucket', value: 'utility:bucket' },
            { title: 'bug', value: 'utility:bug' },
            { title: 'builder', value: 'utility:builder' },
            { title: 'button_choice', value: 'utility:button_choice' },
            { title: 'call', value: 'utility:call' },
            { title: 'campaign', value: 'utility:campaign' },
            {
                title: 'cancel_file_request',
                value: 'utility:cancel_file_request'
            },
            { title: 'cancel_transfer', value: 'utility:cancel_transfer' },
            { title: 'capslock', value: 'utility:capslock' },
            { title: 'cart', value: 'utility:cart' },
            { title: 'case', value: 'utility:case' },
            { title: 'cases', value: 'utility:cases' },
            { title: 'center_align_text', value: 'utility:center_align_text' },
            { title: 'change_owner', value: 'utility:change_owner' },
            {
                title: 'change_record_type',
                value: 'utility:change_record_type'
            },
            { title: 'chart', value: 'utility:chart' },
            { title: 'chat', value: 'utility:chat' },
            { title: 'check', value: 'utility:check' },
            { title: 'checkin', value: 'utility:checkin' },
            { title: 'checkout', value: 'utility:checkout' },
            { title: 'chevrondown', value: 'utility:chevrondown' },
            { title: 'chevronleft', value: 'utility:chevronleft' },
            { title: 'chevronright', value: 'utility:chevronright' },
            { title: 'chevronup', value: 'utility:chevronup' },
            { title: 'choice', value: 'utility:choice' },
            { title: 'classic_interface', value: 'utility:classic_interface' },
            { title: 'clear', value: 'utility:clear' },
            { title: 'clock', value: 'utility:clock' },
            { title: 'close', value: 'utility:close' },
            { title: 'collapse_all', value: 'utility:collapse_all' },
            {
                title: 'collection_variable',
                value: 'utility:collection_variable'
            },
            { title: 'collection', value: 'utility:collection' },
            { title: 'color_swatch', value: 'utility:color_swatch' },
            { title: 'comments', value: 'utility:comments' },
            { title: 'company', value: 'utility:company' },
            {
                title: 'component_customization',
                value: 'utility:component_customization'
            },
            { title: 'connected_apps', value: 'utility:connected_apps' },
            { title: 'constant', value: 'utility:constant' },
            { title: 'contact_request', value: 'utility:contact_request' }
        ],
        iconsExtended: [
            { title: 'contract_alt', value: 'utility:contract_alt' },
            { title: 'contract', value: 'utility:contract' },
            { title: 'copy_to_clipboard', value: 'utility:copy_to_clipboard' },
            { title: 'copy', value: 'utility:copy' },
            { title: 'crossfilter', value: 'utility:crossfilter' },
            { title: 'currency_input', value: 'utility:currency_input' },
            { title: 'currency', value: 'utility:currency' },
            { title: 'custom_apps', value: 'utility:custom_apps' },
            { title: 'cut', value: 'utility:cut' },
            { title: 'dash', value: 'utility:dash' },
            { title: 'data_mapping', value: 'utility:data_mapping' },
            { title: 'database', value: 'utility:database' },
            { title: 'datadotcom', value: 'utility:datadotcom' },
            { title: 'date_input', value: 'utility:date_input' },
            { title: 'date_time', value: 'utility:date_time' },
            { title: 'dayview', value: 'utility:dayview' },
            { title: 'delete', value: 'utility:delete' },
            { title: 'deprecate', value: 'utility:deprecate' },
            { title: 'description', value: 'utility:description' },
            { title: 'desktop_and_phone', value: 'utility:desktop_and_phone' },
            { title: 'desktop_console', value: 'utility:desktop_console' },
            { title: 'desktop', value: 'utility:desktop' },
            { title: 'dialing', value: 'utility:dialing' },
            { title: 'diamond', value: 'utility:diamond' },
            { title: 'dislike', value: 'utility:dislike' },
            { title: 'display_rich_text', value: 'utility:display_rich_text' },
            { title: 'display_text', value: 'utility:display_text' },
            { title: 'dock_panel', value: 'utility:dock_panel' },
            { title: 'down', value: 'utility:down' },
            { title: 'download', value: 'utility:download' },
            { title: 'drag_and_drop', value: 'utility:drag_and_drop' },
            { title: 'drag', value: 'utility:drag' },
            {
                title: 'dynamic_record_choice',
                value: 'utility:dynamic_record_choice'
            },
            { title: 'edit_form', value: 'utility:edit_form' },
            { title: 'edit', value: 'utility:edit' },
            { title: 'education', value: 'utility:education' },
            { title: 'einstein', value: 'utility:einstein' },
            { title: 'email_open', value: 'utility:email_open' },
            { title: 'email', value: 'utility:email' },
            { title: 'emoji', value: 'utility:emoji' },
            { title: 'end_call', value: 'utility:end_call' },
            { title: 'end_chat', value: 'utility:end_chat' },
            {
                title: 'end_messaging_session',
                value: 'utility:end_messaging_session'
            },
            { title: 'engage', value: 'utility:engage' },
            { title: 'enter', value: 'utility:enter' },
            { title: 'erect_window', value: 'utility:erect_window' },
            { title: 'error', value: 'utility:error' },
            { title: 'event_ext', value: 'utility:event_ext' },
            { title: 'event', value: 'utility:event' },
            { title: 'events', value: 'utility:events' },
            { title: 'expand_all', value: 'utility:expand_all' },
            { title: 'expand_alt', value: 'utility:expand_alt' },
            { title: 'expand', value: 'utility:expand' },
            { title: 'fallback', value: 'utility:fallback' },
            { title: 'favorite', value: 'utility:favorite' },
            { title: 'feed', value: 'utility:feed' },
            { title: 'file', value: 'utility:file' },
            {
                title: 'filter_criteria_rule',
                value: 'utility:filter_criteria_rule'
            },
            { title: 'filter_criteria', value: 'utility:filter_criteria' },
            { title: 'filter', value: 'utility:filter' },
            { title: 'filterList', value: 'utility:filterList' },
            { title: 'flow_alt', value: 'utility:flow_alt' },
            { title: 'flow', value: 'utility:flow' },
            { title: 'food_and_drink', value: 'utility:food_and_drink' },
            { title: 'form', value: 'utility:form' },
            { title: 'formula', value: 'utility:formula' },
            { title: 'forward_up', value: 'utility:forward_up' },
            { title: 'forward', value: 'utility:forward' },
            { title: 'freeze_column', value: 'utility:freeze_column' },
            { title: 'frozen', value: 'utility:frozen' },
            { title: 'fulfillment_order', value: 'utility:fulfillment_order' },
            { title: 'full_width_view', value: 'utility:full_width_view' },
            { title: 'global_constant', value: 'utility:global_constant' },
            { title: 'graph', value: 'utility:graph' },
            { title: 'groups', value: 'utility:groups' },
            { title: 'help_center', value: 'utility:help_center' },
            { title: 'help_doc_ext', value: 'utility:help_doc_ext' },
            { title: 'help', value: 'utility:help' },
            { title: 'hide_mobile', value: 'utility:hide_mobile' },
            { title: 'hide', value: 'utility:hide' },
            { title: 'hierarchy', value: 'utility:hierarchy' },
            {
                title: 'high_velocity_sales',
                value: 'utility:high_velocity_sales'
            },
            {
                title: 'holiday_operating_hours',
                value: 'utility:holiday_operating_hours'
            },
            { title: 'home', value: 'utility:home' },
            { title: 'identity', value: 'utility:identity' },
            { title: 'image', value: 'utility:image' },
            { title: 'in_app_assistant', value: 'utility:in_app_assistant' },
            { title: 'inbox', value: 'utility:inbox' },
            { title: 'incoming_call', value: 'utility:incoming_call' },
            { title: 'info_alt', value: 'utility:info_alt' },
            { title: 'info', value: 'utility:info' },
            { title: 'insert_tag_field', value: 'utility:insert_tag_field' },
            { title: 'insert_template', value: 'utility:insert_template' },
            { title: 'inspector_panel', value: 'utility:inspector_panel' },
            { title: 'internal_share', value: 'utility:internal_share' },
            { title: 'italic', value: 'utility:italic' },
            { title: 'jump_to_bottom', value: 'utility:jump_to_bottom' },
            { title: 'jump_to_left', value: 'utility:jump_to_left' },
            { title: 'jump_to_right', value: 'utility:jump_to_right' },
            { title: 'jump_to_top', value: 'utility:jump_to_top' },
            { title: 'justify_text', value: 'utility:justify_text' },
            { title: 'kanban', value: 'utility:kanban' },
            { title: 'key_dates', value: 'utility:key_dates' },
            { title: 'key', value: 'utility:key' },
            { title: 'keyboard_dismiss', value: 'utility:keyboard_dismiss' },
            { title: 'keypad', value: 'utility:keypad' },
            { title: 'knowledge_base', value: 'utility:knowledge_base' },
            { title: 'layers', value: 'utility:layers' },
            { title: 'layout', value: 'utility:layout' },
            { title: 'leave_conference', value: 'utility:leave_conference' },
            { title: 'left_align_text', value: 'utility:left_align_text' },
            { title: 'left', value: 'utility:left' },
            { title: 'level_down', value: 'utility:level_down' },
            { title: 'level_up', value: 'utility:level_up' },
            { title: 'light_bulb', value: 'utility:light_bulb' },
            {
                title: 'lightning_extension',
                value: 'utility:lightning_extension'
            },
            {
                title: 'lightning_inspector',
                value: 'utility:lightning_inspector'
            },
            { title: 'like', value: 'utility:like' },
            { title: 'link', value: 'utility:link' },
            { title: 'linked', value: 'utility:linked' },
            { title: 'list', value: 'utility:list' },
            { title: 'listen', value: 'utility:listen' },
            { title: 'live_message', value: 'utility:live_message' },
            { title: 'location_permit', value: 'utility:location_permit' },
            { title: 'location', value: 'utility:location' },
            { title: 'lock', value: 'utility:lock' },
            {
                title: 'locker_service_api_viewer',
                value: 'utility:locker_service_api_viewer'
            },
            {
                title: 'locker_service_console',
                value: 'utility:locker_service_console'
            },
            { title: 'log_a_call', value: 'utility:log_a_call' },
            { title: 'logout', value: 'utility:logout' },
            { title: 'loop', value: 'utility:loop' },
            { title: 'lower_flag', value: 'utility:lower_flag' },
            { title: 'macros', value: 'utility:macros' },
            { title: 'magicwand', value: 'utility:magicwand' },
            { title: 'mark_all_as_read', value: 'utility:mark_all_as_read' },
            { title: 'matrix', value: 'utility:matrix' },
            {
                title: 'meet_content_source',
                value: 'utility:meet_content_source'
            },
            {
                title: 'meet_focus_content',
                value: 'utility:meet_focus_content'
            },
            { title: 'meet_focus_equal', value: 'utility:meet_focus_equal' },
            {
                title: 'meet_focus_presenter',
                value: 'utility:meet_focus_presenter'
            },
            {
                title: 'meet_present_panel',
                value: 'utility:meet_present_panel'
            },
            { title: 'merge_field', value: 'utility:merge_field' },
            { title: 'merge', value: 'utility:merge' },
            { title: 'metrics', value: 'utility:metrics' },
            { title: 'minimize_window', value: 'utility:minimize_window' },
            { title: 'missed_call', value: 'utility:missed_call' },
            { title: 'money', value: 'utility:money' },
            { title: 'moneybag', value: 'utility:moneybag' },
            { title: 'monthlyview', value: 'utility:monthlyview' },
            { title: 'move', value: 'utility:move' },
            { title: 'multi_picklist', value: 'utility:multi_picklist' },
            {
                title: 'multi_select_checkbox',
                value: 'utility:multi_select_checkbox'
            },
            { title: 'muted', value: 'utility:muted' },
            {
                title: 'new_direct_message',
                value: 'utility:new_direct_message'
            },
            { title: 'new_window', value: 'utility:new_window' },
            { title: 'new', value: 'utility:new' },
            { title: 'news', value: 'utility:news' },
            { title: 'note', value: 'utility:note' },
            { title: 'notebook', value: 'utility:notebook' },
            { title: 'notification', value: 'utility:notification' },
            { title: 'number_input', value: 'utility:number_input' },
            { title: 'office365', value: 'utility:office365' },
            { title: 'offline_briefcase', value: 'utility:offline_briefcase' },
            { title: 'offline_cached', value: 'utility:offline_cached' },
            { title: 'offline', value: 'utility:offline' },
            { title: 'omni_channel', value: 'utility:omni_channel' },
            { title: 'open_folder', value: 'utility:open_folder' },
            { title: 'open', value: 'utility:open' },
            { title: 'opened_folder', value: 'utility:opened_folder' },
            { title: 'outbound_call', value: 'utility:outbound_call' },
            { title: 'outcome', value: 'utility:outcome' },
            { title: 'overflow', value: 'utility:overflow' },
            { title: 'package_org_beta', value: 'utility:package_org_beta' },
            { title: 'package_org', value: 'utility:package_org' },
            { title: 'package', value: 'utility:package' },
            { title: 'page', value: 'utility:page' },
            { title: 'palette', value: 'utility:palette' },
            { title: 'password', value: 'utility:password' },
            { title: 'paste', value: 'utility:paste' },
            { title: 'pause_alt', value: 'utility:pause_alt' },
            { title: 'pause', value: 'utility:pause' },
            { title: 'payment_gateway', value: 'utility:payment_gateway' },
            { title: 'pdf_ext', value: 'utility:pdf_ext' },
            { title: 'people', value: 'utility:people' },
            { title: 'percent', value: 'utility:percent' },
            { title: 'phone_landscape', value: 'utility:phone_landscape' },
            { title: 'phone_portrait', value: 'utility:phone_portrait' },
            { title: 'photo', value: 'utility:photo' },
            { title: 'picklist_choice', value: 'utility:picklist_choice' },
            { title: 'picklist_type', value: 'utility:picklist_type' },
            { title: 'picklist', value: 'utility:picklist' },
            { title: 'pin', value: 'utility:pin' },
            { title: 'pinned', value: 'utility:pinned' },
            { title: 'planning_poker', value: 'utility:planning_poker' },
            { title: 'play', value: 'utility:play' },
            { title: 'podcast_webinar', value: 'utility:podcast_webinar' },
            { title: 'pop_in', value: 'utility:pop_in' },
            { title: 'power', value: 'utility:power' },
            { title: 'preview', value: 'utility:preview' },
            {
                title: 'price_book_entries',
                value: 'utility:price_book_entries'
            },
            { title: 'price_books', value: 'utility:price_books' },
            { title: 'pricing_workspace', value: 'utility:pricing_workspace' },
            { title: 'print', value: 'utility:print' },
            { title: 'priority', value: 'utility:priority' },
            { title: 'privately_shared', value: 'utility:privately_shared' },
            { title: 'process', value: 'utility:process' },
            {
                title: 'product_service_campaign_item',
                value: 'utility:product_service_campaign_item'
            },
            {
                title: 'product_service_campaign',
                value: 'utility:product_service_campaign'
            },
            {
                title: 'product_warranty_term',
                value: 'utility:product_warranty_term'
            },
            { title: 'product_workspace', value: 'utility:product_workspace' },
            { title: 'products', value: 'utility:products' },
            { title: 'prompt_edit', value: 'utility:prompt_edit' },
            { title: 'prompt', value: 'utility:prompt' },
            { title: 'push', value: 'utility:push' },
            { title: 'puzzle', value: 'utility:puzzle' },
            { title: 'question_mark', value: 'utility:question_mark' },
            { title: 'question', value: 'utility:question' },
            {
                title: 'questions_and_answers',
                value: 'utility:questions_and_answers'
            },
            { title: 'quick_text', value: 'utility:quick_text' },
            { title: 'quip', value: 'utility:quip' },
            { title: 'quotation_marks', value: 'utility:quotation_marks' },
            { title: 'quote', value: 'utility:quote' },
            { title: 'radio_button', value: 'utility:radio_button' },
            { title: 'rating', value: 'utility:rating' },
            { title: 'reassign', value: 'utility:reassign' },
            { title: 'recipe', value: 'utility:recipe' },
            { title: 'record_create', value: 'utility:record_create' },
            { title: 'record_delete', value: 'utility:record_delete' },
            { title: 'record_lookup', value: 'utility:record_lookup' },
            { title: 'record_update', value: 'utility:record_update' },
            { title: 'record', value: 'utility:record' },
            {
                title: 'recurring_exception',
                value: 'utility:recurring_exception'
            },
            { title: 'recycle_bin_empty', value: 'utility:recycle_bin_empty' },
            { title: 'recycle_bin_full', value: 'utility:recycle_bin_full' },
            { title: 'redo', value: 'utility:redo' },
            { title: 'refresh', value: 'utility:refresh' },
            { title: 'relate', value: 'utility:relate' },
            { title: 'reminder', value: 'utility:reminder' },
            { title: 'remove_formatting', value: 'utility:remove_formatting' },
            { title: 'remove_link', value: 'utility:remove_link' },
            { title: 'replace', value: 'utility:replace' },
            { title: 'reply_all', value: 'utility:reply_all' },
            { title: 'reply', value: 'utility:reply' },
            { title: 'report_issue', value: 'utility:report_issue' },
            { title: 'reset_password', value: 'utility:reset_password' },
            { title: 'resource_absence', value: 'utility:resource_absence' },
            { title: 'resource_capacity', value: 'utility:resource_capacity' },
            {
                title: 'resource_territory',
                value: 'utility:resource_territory'
            },
            { title: 'retail_execution', value: 'utility:retail_execution' },
            { title: 'retweet', value: 'utility:retweet' },
            { title: 'ribbon', value: 'utility:ribbon' },
            {
                title: 'richtextbulletedlist',
                value: 'utility:richtextbulletedlist'
            },
            { title: 'richtextindent', value: 'utility:richtextindent' },
            {
                title: 'richtextnumberedlist',
                value: 'utility:richtextnumberedlist'
            },
            { title: 'richtextoutdent', value: 'utility:richtextoutdent' },
            { title: 'right_align_text', value: 'utility:right_align_text' },
            { title: 'right', value: 'utility:right' },
            { title: 'rotate', value: 'utility:rotate' },
            { title: 'routing_offline', value: 'utility:routing_offline' },
            { title: 'rows', value: 'utility:rows' },
            { title: 'rules', value: 'utility:rules' },
            { title: 'salesforce_page', value: 'utility:salesforce_page' },
            { title: 'salesforce1', value: 'utility:salesforce1' },
            { title: 'save', value: 'utility:save' },
            { title: 'screen', value: 'utility:screen' },
            { title: 'search', value: 'utility:search' },
            { title: 'section', value: 'utility:section' },
            { title: 'send', value: 'utility:send' },
            {
                title: 'sentiment_negative',
                value: 'utility:sentiment_negative'
            },
            { title: 'sentiment_neutral', value: 'utility:sentiment_neutral' },
            {
                title: 'serialized_product_transaction',
                value: 'utility:serialized_product_transaction'
            },
            {
                title: 'serialized_product',
                value: 'utility:serialized_product'
            },
            { title: 'settings', value: 'utility:settings' },
            {
                title: 'setup_assistant_guide',
                value: 'utility:setup_assistant_guide'
            },
            { title: 'setup_modal', value: 'utility:setup_modal' },
            { title: 'setup', value: 'utility:setup' },
            { title: 'share_file', value: 'utility:share_file' },
            { title: 'share_mobile', value: 'utility:share_mobile' },
            { title: 'share_post', value: 'utility:share_post' },
            { title: 'share', value: 'utility:share' },
            { title: 'shield', value: 'utility:shield' },
            {
                title: 'shift_pattern_entry',
                value: 'utility:shift_pattern_entry'
            },
            { title: 'shift_pattern', value: 'utility:shift_pattern' },
            { title: 'shift_ui', value: 'utility:shift_ui' },
            { title: 'shopping_bag', value: 'utility:shopping_bag' },
            { title: 'shortcuts', value: 'utility:shortcuts' },
            { title: 'side_list', value: 'utility:side_list' },
            { title: 'signpost', value: 'utility:signpost' },
            { title: 'skip_back', value: 'utility:skip_back' },
            { title: 'skip_forward', value: 'utility:skip_forward' },
            { title: 'skip', value: 'utility:skip' },
            { title: 'slider', value: 'utility:slider' },
            { title: 'smiley_and_people', value: 'utility:smiley_and_people' },
            { title: 'sms', value: 'utility:sms' },
            { title: 'snippet', value: 'utility:snippet' },
            {
                title: 'sobject_collection',
                value: 'utility:sobject_collection'
            },
            { title: 'sobject', value: 'utility:sobject' },
            { title: 'socialshare', value: 'utility:socialshare' },
            { title: 'sort', value: 'utility:sort' },
            { title: 'spinner', value: 'utility:spinner' },
            { title: 'stage_collection', value: 'utility:stage_collection' },
            { title: 'stage', value: 'utility:stage' },
            { title: 'standard_objects', value: 'utility:standard_objects' },
            { title: 'steps', value: 'utility:steps' },
            { title: 'stop', value: 'utility:stop' },
            { title: 'store', value: 'utility:store' },
            { title: 'strategy', value: 'utility:strategy' },
            { title: 'strikethrough', value: 'utility:strikethrough' },
            { title: 'success', value: 'utility:success' },
            { title: 'summary', value: 'utility:summary' },
            { title: 'summarydetail', value: 'utility:summarydetail' },
            { title: 'survey', value: 'utility:survey' },
            { title: 'swarm_request', value: 'utility:swarm_request' },
            { title: 'switch', value: 'utility:switch' },
            { title: 'symbols', value: 'utility:symbols' },
            { title: 'sync', value: 'utility:sync' },
            {
                title: 'system_and_global_variable',
                value: 'utility:system_and_global_variable'
            },
            { title: 'table_settings', value: 'utility:table_settings' },
            { title: 'table', value: 'utility:table' },
            { title: 'tablet_landscape', value: 'utility:tablet_landscape' },
            { title: 'tablet_portrait', value: 'utility:tablet_portrait' },
            { title: 'tabset', value: 'utility:tabset' },
            { title: 'target', value: 'utility:target' },
            { title: 'task', value: 'utility:task' },
            {
                title: 'text_background_color',
                value: 'utility:text_background_color'
            },
            { title: 'text_color', value: 'utility:text_color' },
            { title: 'text_template', value: 'utility:text_template' },
            { title: 'text', value: 'utility:text' },
            { title: 'textarea', value: 'utility:textarea' },
            { title: 'textbox', value: 'utility:textbox' },
            {
                title: 'threedots_vertical',
                value: 'utility:threedots_vertical'
            },
            { title: 'threedots', value: 'utility:threedots' },
            { title: 'thunder', value: 'utility:thunder' },
            { title: 'tile_card_list', value: 'utility:tile_card_list' },
            {
                title: 'toggle_panel_bottom',
                value: 'utility:toggle_panel_bottom'
            },
            { title: 'toggle_panel_left', value: 'utility:toggle_panel_left' },
            {
                title: 'toggle_panel_right',
                value: 'utility:toggle_panel_right'
            },
            { title: 'toggle_panel_top', value: 'utility:toggle_panel_top' },
            { title: 'toggle', value: 'utility:toggle' },
            { title: 'topic', value: 'utility:topic' },
            { title: 'topic2', value: 'utility:topic2' },
            { title: 'touch_action', value: 'utility:touch_action' },
            { title: 'tracker', value: 'utility:tracker' },
            { title: 'trail', value: 'utility:trail' },
            { title: 'trailblazer_ext', value: 'utility:trailblazer_ext' },
            { title: 'trailhead_alt', value: 'utility:trailhead_alt' },
            { title: 'trailhead_ext', value: 'utility:trailhead_ext' },
            { title: 'trailhead', value: 'utility:trailhead' },
            { title: 'travel_and_places', value: 'utility:travel_and_places' },
            { title: 'trending', value: 'utility:trending' },
            {
                title: 'turn_off_notifications',
                value: 'utility:turn_off_notifications'
            },
            { title: 'type_tool', value: 'utility:type_tool' },
            { title: 'type', value: 'utility:type' },
            { title: 'undelete', value: 'utility:undelete' },
            { title: 'undeprecate', value: 'utility:undeprecate' },
            { title: 'underline', value: 'utility:underline' },
            { title: 'undo', value: 'utility:undo' },
            { title: 'unlinked', value: 'utility:unlinked' },
            { title: 'unlock', value: 'utility:unlock' },
            { title: 'unmuted', value: 'utility:unmuted' },
            { title: 'up', value: 'utility:up' },
            { title: 'upload', value: 'utility:upload' },
            { title: 'user_role', value: 'utility:user_role' },
            { title: 'user', value: 'utility:user' },
            { title: 'variable', value: 'utility:variable' },
            {
                title: 'variation_attribute_setup',
                value: 'utility:variation_attribute_setup'
            },
            {
                title: 'variation_products',
                value: 'utility:variation_products'
            },
            { title: 'video', value: 'utility:video' },
            { title: 'voicemail_drop', value: 'utility:voicemail_drop' },
            { title: 'volume_high', value: 'utility:volume_high' },
            { title: 'volume_low', value: 'utility:volume_low' },
            { title: 'volume_off', value: 'utility:volume_off' },
            { title: 'waits', value: 'utility:waits' },
            { title: 'warning', value: 'utility:warning' },
            { title: 'warranty_term', value: 'utility:warranty_term' },
            { title: 'watchlist', value: 'utility:watchlist' },
            { title: 'weeklyview', value: 'utility:weeklyview' },
            { title: 'wifi', value: 'utility:wifi' },
            { title: 'work_order_type', value: 'utility:work_order_type' },
            { title: 'world', value: 'utility:world' },
            { title: 'yubi_key', value: 'utility:yubi_key' },
            { title: 'zoomin', value: 'utility:zoomin' },
            { title: 'zoomout', value: 'utility:zoomout' }
        ]
    },
    {
        title: 'Doctype',
        value: 'doctype',
        icons: [
            { title: 'ai', value: 'doctype:ai' },
            { title: 'attachment', value: 'doctype:attachment' },
            { title: 'audio', value: 'doctype:audio' },
            { title: 'box_notes', value: 'doctype:box_notes' },
            { title: 'csv', value: 'doctype:csv' },
            { title: 'eps', value: 'doctype:eps' },
            { title: 'excel', value: 'doctype:excel' },
            { title: 'exe', value: 'doctype:exe' },
            { title: 'flash', value: 'doctype:flash' },
            { title: 'folder', value: 'doctype:folder' },
            { title: 'gdoc', value: 'doctype:gdoc' },
            { title: 'gdocs', value: 'doctype:gdocs' },
            { title: 'gform', value: 'doctype:gform' },
            { title: 'gpres', value: 'doctype:gpres' },
            { title: 'gsheet', value: 'doctype:gsheet' },
            { title: 'html', value: 'doctype:html' },
            { title: 'image', value: 'doctype:image' },
            { title: 'keynote', value: 'doctype:keynote' },
            { title: 'library_folder', value: 'doctype:library_folder' },
            { title: 'link', value: 'doctype:link' },
            { title: 'mp4', value: 'doctype:mp4' },
            { title: 'overlay', value: 'doctype:overlay' },
            { title: 'pack', value: 'doctype:pack' },
            { title: 'pages', value: 'doctype:pages' },
            { title: 'pdf', value: 'doctype:pdf' },
            { title: 'ppt', value: 'doctype:ppt' },
            { title: 'psd', value: 'doctype:psd' },
            { title: 'quip_doc', value: 'doctype:quip_doc' },
            { title: 'quip_sheet', value: 'doctype:quip_sheet' },
            { title: 'quip_slide', value: 'doctype:quip_slide' },
            { title: 'rtf', value: 'doctype:rtf' },
            { title: 'slide', value: 'doctype:slide' },
            { title: 'stypi', value: 'doctype:stypi' },
            { title: 'txt', value: 'doctype:txt' },
            { title: 'unknown', value: 'doctype:unknown' },
            { title: 'video', value: 'doctype:video' },
            { title: 'visio', value: 'doctype:visio' },
            { title: 'webex', value: 'doctype:webex' },
            { title: 'word', value: 'doctype:word' },
            { title: 'xml', value: 'doctype:xml' },
            { title: 'zip', value: 'doctype:zip' }
        ]
    },
    {
        title: 'Action',
        value: 'action',
        icons: [
            { title: 'add_contact', value: 'action:add_contact' },
            { title: 'add_file', value: 'action:add_file' },
            { title: 'add_photo_video', value: 'action:add_photo_video' },
            { title: 'add_relationship', value: 'action:add_relationship' },
            { title: 'adjust_value', value: 'action:adjust_value' },
            { title: 'announcement', value: 'action:announcement' },
            { title: 'apex', value: 'action:apex' },
            { title: 'approval', value: 'action:approval' },
            { title: 'back', value: 'action:back' },
            { title: 'bug', value: 'action:bug' },
            { title: 'call', value: 'action:call' },
            { title: 'canvas', value: 'action:canvas' },
            { title: 'change_owner', value: 'action:change_owner' },
            { title: 'change_record_type', value: 'action:change_record_type' },
            { title: 'check', value: 'action:check' },
            { title: 'clone', value: 'action:clone' },
            { title: 'close', value: 'action:close' },
            { title: 'defer', value: 'action:defer' },
            { title: 'delete', value: 'action:delete' },
            { title: 'description', value: 'action:description' },
            { title: 'dial_in', value: 'action:dial_in' },
            { title: 'download', value: 'action:download' },
            { title: 'edit_groups', value: 'action:edit_groups' },
            { title: 'edit_relationship', value: 'action:edit_relationship' },
            { title: 'edit', value: 'action:edit' },
            { title: 'email', value: 'action:email' },
            { title: 'fallback', value: 'action:fallback' },
            { title: 'filter', value: 'action:filter' },
            { title: 'flow', value: 'action:flow' },
            { title: 'follow', value: 'action:follow' },
            { title: 'following', value: 'action:following' },
            { title: 'freeze_user', value: 'action:freeze_user' },
            { title: 'goal', value: 'action:goal' },
            { title: 'google_news', value: 'action:google_news' },
            { title: 'info', value: 'action:info' },
            { title: 'join_group', value: 'action:join_group' },
            { title: 'lead_convert', value: 'action:lead_convert' },
            { title: 'leave_group', value: 'action:leave_group' },
            { title: 'log_a_call', value: 'action:log_a_call' },
            { title: 'log_event', value: 'action:log_event' },
            { title: 'manage_perm_sets', value: 'action:manage_perm_sets' },
            { title: 'map', value: 'action:map' },
            { title: 'more', value: 'action:more' },
            { title: 'new_account', value: 'action:new_account' },
            { title: 'new_campaign', value: 'action:new_campaign' },
            { title: 'new_case', value: 'action:new_case' },
            { title: 'new_child_case', value: 'action:new_child_case' },
            { title: 'new_contact', value: 'action:new_contact' },
            { title: 'new_event', value: 'action:new_event' },
            { title: 'new_group', value: 'action:new_group' },
            { title: 'new_lead', value: 'action:new_lead' },
            { title: 'new_note', value: 'action:new_note' },
            { title: 'new_notebook', value: 'action:new_notebook' },
            { title: 'new_opportunity', value: 'action:new_opportunity' },
            { title: 'new_person_account', value: 'action:new_person_account' },
            { title: 'new_task', value: 'action:new_task' },
            { title: 'new', value: 'action:new' },
            { title: 'password_unlock', value: 'action:password_unlock' },
            { title: 'preview', value: 'action:preview' },
            { title: 'priority', value: 'action:priority' },
            {
                title: 'question_post_action',
                value: 'action:question_post_action'
            },
            { title: 'quote', value: 'action:quote' },
            { title: 'recall', value: 'action:recall' },
            { title: 'record', value: 'action:record' },
            { title: 'refresh', value: 'action:refresh' },
            { title: 'reject', value: 'action:reject' },
            {
                title: 'remove_relationship',
                value: 'action:remove_relationship'
            },
            { title: 'remove', value: 'action:remove' },
            { title: 'reset_password', value: 'action:reset_password' },
            { title: 'script', value: 'action:script' },
            { title: 'share_file', value: 'action:share_file' },
            { title: 'share_link', value: 'action:share_link' },
            { title: 'share_poll', value: 'action:share_poll' },
            { title: 'share_post', value: 'action:share_post' },
            { title: 'share_thanks', value: 'action:share_thanks' },
            { title: 'share', value: 'action:share' },
            { title: 'sort', value: 'action:sort' },
            {
                title: 'submit_for_approval',
                value: 'action:submit_for_approval'
            },
            { title: 'update_status', value: 'action:update_status' },
            { title: 'update', value: 'action:update' },
            { title: 'upload', value: 'action:upload' },
            { title: 'user_activation', value: 'action:user_activation' },
            { title: 'user', value: 'action:user' },
            { title: 'view_relationship', value: 'action:view_relationship' },
            { title: 'web_link', value: 'action:web_link' }
        ]
    }
];

export { ICON_TYPES };
